# Generated by Django 4.1.5 on 2023-01-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liked',
            name='post',
        ),
        migrations.RemoveField(
            model_name='liked',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Liked',
        ),
    ]
