# Generated by Django 4.1.5 on 2023-01-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='id',
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
