# Generated by Django 4.1.5 on 2023-01-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_blog_id_alter_blog_post_user_alter_blog_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('programming', 'Programming'), ('datascience', 'Data Science'), ('healthcare', 'Health Care')], default='All', max_length=25),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
