# Generated by Django 4.1.5 on 2023-01-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_blog_options_alter_blog_category_bloglike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='action',
            field=models.CharField(default='unlike', max_length=7),
        ),
    ]
