# Generated by Django 4.1.5 on 2023-01-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_blog_action_blogcomment_blog_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='comment',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
